language: python
install: 
  - make bootstrap
script: make
branches:
  except:
    - /^v[0-9]/
after_success: coveralls
before_install:
  - sudo apt-get update
  - sudo apt-get -y install npm
  - nvm install 12
  - npm install --global yarn